### ISSUE TITLE
1.12.2 support

### ISSUE THREAD

**Issue by MakerTim** [Indemnity83/irontank#46]
Is an update to 1.12.x planned?

**Comment by Indemnity83** [comment]
Yes it is. Will be starting work on it this weekend. Not sure yet how long it will take. My understanding is the changes in Buildcraft will not pose any problem. But Forge made some big changes that I have to work though.

**Comment by MakerTim** [comment]
Is it a lot of work?
(No pressure, just wondering <3 )

**Comment by Indemnity83** [comment]
Turned out to be a bit of trouble; I think because the structure of the MOD wasn't very good in 1.11. I've got some restructuring I'll push to the 1.11 branch which may help me with the migration. 

I have had the mod compile in 1.12, but haven't got the recipes working yet. Documentation for Forge is atrocious, so Its a bit of trial and error.

**Comment by Indemnity83** [comment]
Full support for 1.12 in 8d9f4310f63be4db18aac7eafdeba90634eb9bd3 

Tagged as 2.1.0 Beta 1 on curse: http://bit.ly/2AYX95K
