### ISSUE TITLE
Recipe Conflict

### ISSUE THREAD

**Issue by cheesits456** [Indemnity83/irontank#50]
The recipe for the gold to diamond tank upgrade conflicts with the recipe for Iron Chest's gold to diamond chest upgrade, making it impossible to craft. I propose rotating the recipe 90 degrees to fix this problem. Theres also probably other recipes that conflict, but I didn't check.

**Comment by Indemnity83** [comment]
Well this is frustrating, this looks like its actually a regression. It was right for a while, then I noticed a variance between the documentation and the mod and changed the mod to match the documentation in 659a33f832619b844dde22f45e0a14caa0fd0b33 

Immediate suggestion is to use https://minecraft.curseforge.com/projects/crafttweaker to compile your modpack with adjusted recipies either for Iron Chests (use wood instead of glass) or Iron Tanks (rotate the recipies). 

I'd like to get some feedback from the community on a long term solution though. I'm not a fan of rotating the recipe because it isn't visually intuitive.

**Comment by seeker2921** [comment]
Set a config option, if the end user finds a conflict with the recipe, they set a variable in configs to rotate 90 degrees, otherwise, it is not a problem and can remain the same.

**Comment by Indemnity83** [comment]
It doesn't look like there is likely going to be movement on Iron Chests changing their recipes. 

Alternate suggestion: What about replacing the glass blocks with glass panes in all the upgrade recipes? This will keep them all consistent and keeps users from having to know about and modify the config in what is honestly a very high likelihood of recipe conflict.

**Comment by Ghent** [comment]
I think the pane solution is a great idea.  I also think the rotation isn't a bad idea, as the glass is horizontal in the recipes currently, and one might think that in a tank, the vertical walls are what are glass.
