### ISSUE TITLE
irontanks-1.1.16.jar missing MC version tag.

### ISSUE THREAD

**Issue by AnrDaemon** [Indemnity83/irontank#60]
The latest uploaded release missing MC version in the name.

I don't think that was intended, does it?

**Comment by Indemnity83** [comment]
It was intentional. I rebuilt my build processes to be consistent across supported versions. 

It should be very clear in all the available download locations what version of Minecraft it’s for.

**Comment by AnrDaemon** [comment]
Except it's not very clear once I have the file downloaded… But as you say…

**Comment by Indemnity83** [comment]
I think you have a fair point though; looking through the top 10 or so mods its pretty standard convention to include the MC version. 

I hadn't actually been putting the version in the filename since Oct of '17 but that was in the 1.11 and 1.12 branches. I'll add it into the build scripts (particularly now that they're all similar build processes this isn't a chore). 

`irontanks-1.7.10-1.1.16.jar` seems appropriate? with the snapshot builds being `irontanks-1.7.10-1.1.16+<git-hash>.jar` or `irontanks-1.7.10-1.1.16+snapshot-<build>.jar`. Would you agree?

**Comment by Indemnity83** [comment]
I made this change in 111401fbbc799f868e7c22edda6163b7082e8259 and merged into all branches; all future releases will be tagged as described above. 

Thanks for the feedback!
