### ISSUE TITLE
Missing Recipes in NEI

### ISSUE THREAD

**Issue by Sempiternity87** [Indemnity83/irontank#8]
There are some missing recipes in NEI:
Copper Tank
Copper to Silver Upgrade
Silver to Diamond Upgrade
Glass to Copper Upgrade
Copper to Iron Upgrade
Silver to Gold Upgrade

**Comment by Indemnity83** [comment]
If you don't have any mod that adds silver or copper to the game (specifically, to the ore dictionary) than there will not be any recipe for these items. They will still be available in creative and show up in NEI however, because the item and block are still registered with the game on initialization. 

This is expected behavior.
