### ISSUE TITLE
Stacking different tanks don't work well together

### ISSUE THREAD

**Issue by Sempiternity87** [Indemnity83/irontank#9]
Stacking a regular glass tank on top of a gold tank, and then adding liquid to the bottom tank also adds the liquid to the upper tank.

**Comment by Sempiternity87** [comment]
Upon further testing, adding liquid to either tank adds it to the other. I should be flowing from the upper tank down.

**Comment by Indemnity83** [comment]
Not sure what you mean by adding liquid to either tank adds it to the other. 

The tank blocks in a stack (regardless of type) are intended to operate as a single tank with a total capacity of the sum of each tank block. So if you stack two tank blocks of different types, it is expected behavior that clicking a bucket on either block should add the liquid to the bottom tank until it is full, then start filling the upper tank.

**Comment by Indemnity83** [comment]
I haven't been able to reproduce this in any way. I'm going to write it off for now. 

If this happens again I'd be very curious to know what the result is of logging out and back in, adding another tank to the stack and trying to remove liquid with an empty bucket.
